import { useSession, getSession } from 'next-auth/react'
import Head from 'next/head'

export default function Home() {
  const { data: session } = useSession()

  if (session) {
    return (
      <>
        <Head>
          <title>TimeLineup</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <h1>Index</h1>
      </>
    )
  }
}

export async function getServerSideProps(context: any) {
  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/auth/signin',
        permanent: false,
      },
    }
  }

  return {
    props: { session },
  }
}
